// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rayneforge.Forecast.Infrastructure.Data;

#nullable disable

namespace Rayneforge.Forecast.Infrastructure.Migrations.SqliteNews
{
    [DbContext(typeof(SqliteNewsDbContext))]
    [Migration("20260208023724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.ArticleClaim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleClaims");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.ArticleClaimEntity", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("ArticleClaimEntities");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "CanonicalName")
                        .IsUnique();

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.Narrative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidencePosture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemporalFocus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WriteUp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Narratives");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.NarrativeClaimLink", b =>
                {
                    b.Property<string>("NarrativeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimId")
                        .HasColumnType("TEXT");

                    b.HasKey("NarrativeId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("NarrativeClaimLinks");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.NarrativeEntityLink", b =>
                {
                    b.Property<string>("NarrativeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("NarrativeId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("NarrativeEntityLinks");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.NewsArticle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeculativeNarrative")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlToImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.ArticleClaim", b =>
                {
                    b.HasOne("Rayneforge.Forecast.Domain.Models.NewsArticle", "Article")
                        .WithMany("Claims")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.ArticleClaimEntity", b =>
                {
                    b.HasOne("Rayneforge.Forecast.Domain.Models.ArticleClaim", "Claim")
                        .WithMany("EntityLinks")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rayneforge.Forecast.Domain.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.NarrativeClaimLink", b =>
                {
                    b.HasOne("Rayneforge.Forecast.Domain.Models.ArticleClaim", "Claim")
                        .WithMany("NarrativeLinks")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rayneforge.Forecast.Domain.Models.Narrative", "Narrative")
                        .WithMany("ClaimLinks")
                        .HasForeignKey("NarrativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Narrative");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.NarrativeEntityLink", b =>
                {
                    b.HasOne("Rayneforge.Forecast.Domain.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rayneforge.Forecast.Domain.Models.Narrative", "Narrative")
                        .WithMany("EntityLinks")
                        .HasForeignKey("NarrativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Narrative");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.NewsArticle", b =>
                {
                    b.OwnsOne("Rayneforge.Forecast.Domain.Models.NewsSource", "Source", b1 =>
                        {
                            b1.Property<string>("NewsArticleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("NewsArticleId");

                            b1.ToTable("NewsArticles");

                            b1.WithOwner()
                                .HasForeignKey("NewsArticleId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.ArticleClaim", b =>
                {
                    b.Navigation("EntityLinks");

                    b.Navigation("NarrativeLinks");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.Narrative", b =>
                {
                    b.Navigation("ClaimLinks");

                    b.Navigation("EntityLinks");
                });

            modelBuilder.Entity("Rayneforge.Forecast.Domain.Models.NewsArticle", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
