// ─────────────────────────────────────────────────────────────────
// deploy.bicep — Orchestrator
//
// Single entry-point for deploying Rayneforge.Forecast infrastructure.
// Deploys the Aspire-generated main.bicep (infra resources).
//
// All files live in infra/azure/bicep/:
//   deploy.bicep  ← this file (orchestrator)
//   main.bicep    ← generated by generate-bicep.ps1
//
// Usage:
//   az deployment sub create \
//     --location eastus2 \
//     --template-file infra/azure/bicep/deploy.bicep \
//     --parameters principalId=<oid> environmentName=rayneforge-dev location=eastus2
//
// Prerequisites:
//   Run infra/azure/scripts/generate-bicep.ps1 locally first to
//   produce main.bicep in this directory, then commit it.
// ─────────────────────────────────────────────────────────────────

targetScope = 'subscription'

// ─── Parameters ─────────────────────────────────────────────────

@description('Object ID of the deploying service principal (passed to the Aspire infra module)')
param principalId string

@minLength(1)
@maxLength(64)
@description('Name of the environment (used for resource group naming)')
param environmentName string

@description('Azure region for all resources')
param location string

// ─── Module 1: Aspire-generated infrastructure ──────────────────
// main.bicep is produced locally by  generate-bicep.ps1  and committed.
// It provisions: Managed Identity, Cosmos DB, Azure OpenAI, Storage,
// Service Bus, Container Apps Environment, Container Registry, etc.
//
// Expected outputs (names must match the generated file):
//   identityPrincipalId    — principal ID of the Aspire managed identity
//   cosmosAccountName      — name of the Cosmos DB account
//   openAiAccountName      — name of the Cognitive Services account
//   storageAccountName     — name of the Storage account
//   serviceBusNamespaceName — name of the Service Bus namespace
//
// If the output names in the generated main.bicep differ, update the
// references in the rbac module below to match.

module infra 'main.bicep' = {
  name: 'aspire-infrastructure'
  params: {
    environmentName: environmentName
    principalId: principalId
    location: location
  }
}

// ─── Outputs ────────────────────────────────────────────────────

@description('Principal ID of the managed identity used by deployed services')
output identityPrincipalId string = infra.outputs.identityPrincipalId
